Tien
jerrylee17/casino pull request #33
Opened 2020-04-19 21:55 UTC by TimTran115

Please double check so I don't mess things up

2020-04-19 23:37 UTC, realCalvin requested changes
Rebase from master. You rebased from Tiffany's branch.
Also, squash commits, https://github.com/wprig/wprig/wiki/How-to-squash-commits

2020-04-20 07:30 UTC, tiffanynn reviewed
just rebase with the master branch and go through the commits first. lines i commented on need to be removed. it took me awhile to get but it'll work out at the end.

2020-04-20 07:30 UTC, tiffanynn commented on blits.sql
> +>>>>>>> 624c6daa8b46cedcda8a1f373cbf5831c8725e49
these need to be gone

2020-04-20 07:30 UTC, tiffanynn commented on blits.sql
> +=======
same with these

2020-04-20 07:30 UTC, tiffanynn commented on blits.sql
> +>>>>>>> 624c6daa8b46cedcda8a1f373cbf5831c8725e49
this needs to be gone

2020-04-20 07:30 UTC, tiffanynn commented on blits.sql
> +=======
same w/ here

2020-04-20 07:30 UTC, tiffanynn commented on blits.sql
> +<<<<<<< HEAD
remove

2020-04-20 07:30 UTC, tiffanynn commented on blits.sql
> +<<<<<<< HEAD
remove

2020-04-20 07:31 UTC, tiffanynn commented on blits.sql
> +>>>>>>> 624c6daa8b46cedcda8a1f373cbf5831c8725e49
only line 69

2020-04-20 21:42 UTC, TimTran115 commented
![Capture](https://user-images.githubusercontent.com/45045430/79802625-26feb500-8315-11ea-8054-8d5ec8c2db18.PNG)
Update profile

2020-04-20 21:57 UTC, TimTran115 commented
I think I updated everything now

2020-04-21 20:39 UTC, realCalvin submitted a review, later dismissed
Some changes:

- Can you make it so this page looks like the other ones? (look at the css/colors used)
- Remove status because that's additional work to do & store
- For game history matches can you put like dummy data, so we can see what it'd look like? (maybe try making it so that losses are displayed as red and wins as green somehow)

2020-04-26 00:57 UTC, hsorathia approved these changes

2020-04-26 01:00 UTC, merged